name: app
description: A project with Appwrite

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.4
  flutter_native_splash: ^2.1.6
  shared_preferences: ^2.0.13
  http: ^0.13.4
  async: ^2.9.0
  flutter_launcher_icons: ^0.9.2
  fluttericon: ^2.0.0
  intl: ^0.17.0
  fluttertoast: ^8.0.9
  liquid_progress_indicator: ^0.4.0
  google_fonts: ^2.3.1
  appwrite: ^4.0.2

dev_dependencies:
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
